.TH "C:/Users/User/Desktop/folder/TreeLib Directory Reference" 3 "Sun May 7 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/User/Desktop/folder/TreeLib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBobj\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAVLNode\&.cs\fP"
.br
.ti -1c
.RI "file \fBAVLTree\&.cs\fP"
.br
.ti -1c
.RI "file \fBBinSearchTree\&.cs\fP"
.br
.ti -1c
.RI "file \fBNode\&.cs\fP"
.br
.in -1c
