.TH "C:/Users/User/Desktop/folder/Main/obj/Debug/net7.0/Main.AssemblyInfo.cs" 3 "Sun May 7 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/User/Desktop/folder/Main/obj/Debug/net7.0/Main.AssemblyInfo.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
