.TH "TreeLib.Node" 3 "Sun May 7 2023" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeLib.Node
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTreeLib\&.AVLNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (int \fBValue\fP)"
.br
.ti -1c
.RI "\fBNode\fP (int \fBKey\fP, int \fBValue\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBKey\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "int \fBValue\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNode\fP \fBLeft\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBNode\fP \fBRight\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TreeLib\&.Node\&.Node (int Value)"

.SS "TreeLib\&.Node\&.Node (int Key, int Value)"

.SH "Property Documentation"
.PP 
.SS "int TreeLib\&.Node\&.Key\fC [get]\fP, \fC [set]\fP"

.SS "\fBNode\fP TreeLib\&.Node\&.Left\fC [get]\fP, \fC [set]\fP"

.SS "\fBNode\fP TreeLib\&.Node\&.Right\fC [get]\fP, \fC [set]\fP"

.SS "int TreeLib\&.Node\&.Value\fC [get]\fP, \fC [set]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
